"""SVG Enhancer service — Phase 10.

Advanced SVG post-processing features:
- Responsive SVG (preserveAspectRatio)
- Accessible SVGs (<title>, <desc>, aria-*)
- SVG minification & cleanup
- Pattern fills for textured regions
- Gradient optimization
- <clipPath> and <mask> grouping
"""

import logging
import re
from typing import Dict, List, Optional
from xml.etree import ElementTree as ET

logger = logging.getLogger(__name__)


class SVGEnhancer:
    """Post-process SVGs for quality, accessibility, and responsiveness."""

    @staticmethod
    def enhance(
        svg_data: bytes,
        title: Optional[str] = None,
        description: Optional[str] = None,
        make_responsive: bool = True,
        add_accessibility: bool = True,
        add_metadata: bool = True,
        minify: bool = False,
        lang: str = "en",
    ) -> bytes:
        """Apply all enhancements to an SVG."""
        root = ET.fromstring(svg_data)
        ET.register_namespace("", "http://www.w3.org/2000/svg")
        ET.register_namespace("xlink", "http://www.w3.org/1999/xlink")
        ns = "http://www.w3.org/2000/svg"

        if make_responsive:
            SVGEnhancer._make_responsive(root)

        if add_accessibility:
            SVGEnhancer._add_accessibility(root, title, description, lang, ns)

        if add_metadata:
            SVGEnhancer._add_metadata(root, ns)

        result = ET.tostring(root, encoding="unicode")

        if minify:
            result = SVGEnhancer._minify(result)

        return result.encode("utf-8")

    @staticmethod
    def _make_responsive(root: ET.Element):
        """Make SVG responsive by using viewBox and removing fixed dimensions."""
        width = root.get("width", "")
        height = root.get("height", "")

        w = float(re.sub(r"[a-z%]+$", "", width, flags=re.I) or "0")
        h = float(re.sub(r"[a-z%]+$", "", height, flags=re.I) or "0")

        if not root.get("viewBox") and w > 0 and h > 0:
            root.set("viewBox", f"0 0 {w} {h}")

        # Remove fixed width/height for responsiveness
        root.set("width", "100%")
        root.set("height", "auto")
        root.set("preserveAspectRatio", "xMidYMid meet")

    @staticmethod
    def _add_accessibility(
        root: ET.Element,
        title: Optional[str],
        description: Optional[str],
        lang: str,
        ns: str,
    ):
        """Add WCAG-compliant accessibility attributes."""
        # Role
        root.set("role", "img")
        root.set("aria-labelledby", "svg-title svg-desc")
        root.set("{http://www.w3.org/XML/1998/namespace}lang", lang)

        # <title> — required for accessibility
        title_text = title or "Vector graphic converted from raster image"
        title_elem = root.find(f"{{{ns}}}title")
        if title_elem is None:
            title_elem = ET.SubElement(root, f"{{{ns}}}title")
            root.insert(0, title_elem)
        title_elem.text = title_text
        title_elem.set("id", "svg-title")

        # <desc>
        desc_text = description or "Scalable vector graphic generated by Raster to SVG Converter"
        desc_elem = root.find(f"{{{ns}}}desc")
        if desc_elem is None:
            desc_elem = ET.SubElement(root, f"{{{ns}}}desc")
            root.insert(1, desc_elem)
        desc_elem.text = desc_text
        desc_elem.set("id", "svg-desc")

    @staticmethod
    def _add_metadata(root: ET.Element, ns: str):
        """Add generator metadata."""
        # Check if metadata already exists
        metadata = root.find(f"{{{ns}}}metadata")
        if metadata is None:
            metadata = ET.SubElement(root, f"{{{ns}}}metadata")

        # Add generator info
        generator = ET.SubElement(metadata, "generator")
        generator.text = "Raster to SVG Converter"
        version = ET.SubElement(metadata, "version")
        version.text = "Phase 10"

    @staticmethod
    def _minify(svg_str: str) -> str:
        """Minify SVG string."""
        # Remove comments
        svg_str = re.sub(r"<!--.*?-->", "", svg_str, flags=re.DOTALL)
        # Collapse whitespace
        svg_str = re.sub(r">\s+<", "><", svg_str)
        svg_str = re.sub(r"\s+", " ", svg_str)
        # Remove unnecessary spaces in attributes
        svg_str = re.sub(r"\s*/\s*>", "/>", svg_str)
        return svg_str.strip()

    @staticmethod
    def add_gradient_defs(
        svg_data: bytes,
        gradients: List[Dict],
    ) -> bytes:
        """Add gradient definitions to SVG.

        gradients: list of {
            "id": "grad1",
            "type": "linear" | "radial",
            "stops": [{"offset": "0%", "color": "#f00", "opacity": 1.0}, ...],
            "x1": "0%", "y1": "0%", "x2": "100%", "y2": "0%",  # for linear
            "cx": "50%", "cy": "50%", "r": "50%",  # for radial
        }
        """
        root = ET.fromstring(svg_data)
        ET.register_namespace("", "http://www.w3.org/2000/svg")
        ns = "http://www.w3.org/2000/svg"

        # Find or create <defs>
        defs = root.find(f"{{{ns}}}defs")
        if defs is None:
            defs = ET.SubElement(root, f"{{{ns}}}defs")
            root.insert(0, defs)

        for grad in gradients:
            grad_type = grad.get("type", "linear")
            grad_id = grad.get("id", f"grad-{id(grad)}")

            if grad_type == "linear":
                elem = ET.SubElement(defs, f"{{{ns}}}linearGradient")
                elem.set("id", grad_id)
                elem.set("x1", grad.get("x1", "0%"))
                elem.set("y1", grad.get("y1", "0%"))
                elem.set("x2", grad.get("x2", "100%"))
                elem.set("y2", grad.get("y2", "0%"))
            else:
                elem = ET.SubElement(defs, f"{{{ns}}}radialGradient")
                elem.set("id", grad_id)
                elem.set("cx", grad.get("cx", "50%"))
                elem.set("cy", grad.get("cy", "50%"))
                elem.set("r", grad.get("r", "50%"))

            for stop in grad.get("stops", []):
                stop_elem = ET.SubElement(elem, f"{{{ns}}}stop")
                stop_elem.set("offset", str(stop.get("offset", "0%")))
                stop_elem.set("stop-color", stop.get("color", "#000"))
                if "opacity" in stop:
                    stop_elem.set("stop-opacity", str(stop["opacity"]))

        return ET.tostring(root, encoding="unicode").encode("utf-8")

    @staticmethod
    def add_clip_paths(
        svg_data: bytes,
        groups: List[Dict],
    ) -> bytes:
        """Add <clipPath> definitions and apply to grouped elements.

        groups: list of {
            "id": "clip1",
            "shape": "rect" | "circle",
            "attrs": {"x": 0, "y": 0, "width": 100, "height": 100},
            "target_ids": ["path1", "path2"],
        }
        """
        root = ET.fromstring(svg_data)
        ET.register_namespace("", "http://www.w3.org/2000/svg")
        ns = "http://www.w3.org/2000/svg"

        defs = root.find(f"{{{ns}}}defs")
        if defs is None:
            defs = ET.SubElement(root, f"{{{ns}}}defs")
            root.insert(0, defs)

        for group in groups:
            clip_id = group.get("id", f"clip-{id(group)}")
            clip_path = ET.SubElement(defs, f"{{{ns}}}clipPath")
            clip_path.set("id", clip_id)

            shape_type = group.get("shape", "rect")
            attrs = group.get("attrs", {})

            shape = ET.SubElement(clip_path, f"{{{ns}}}{shape_type}")
            for k, v in attrs.items():
                shape.set(k, str(v))

            # Apply clip-path to targets
            for target_id in group.get("target_ids", []):
                for elem in root.iter():
                    if elem.get("id") == target_id:
                        elem.set("clip-path", f"url(#{clip_id})")

        return ET.tostring(root, encoding="unicode").encode("utf-8")

    @staticmethod
    def get_svg_stats(svg_data: bytes) -> Dict:
        """Analyze SVG and return statistics."""
        root = ET.fromstring(svg_data)

        stats = {
            "total_elements": 0,
            "paths": 0,
            "circles": 0,
            "rects": 0,
            "polygons": 0,
            "lines": 0,
            "groups": 0,
            "gradients": 0,
            "clip_paths": 0,
            "text_elements": 0,
            "has_animations": False,
            "has_accessibility": False,
            "has_viewbox": bool(root.get("viewBox")),
            "is_responsive": root.get("width", "").endswith("%"),
            "size_bytes": len(svg_data),
        }

        for elem in root.iter():
            tag = elem.tag.split("}")[-1] if "}" in elem.tag else elem.tag
            stats["total_elements"] += 1

            if tag == "path":
                stats["paths"] += 1
            elif tag == "circle" or tag == "ellipse":
                stats["circles"] += 1
            elif tag == "rect":
                stats["rects"] += 1
            elif tag in ("polygon", "polyline"):
                stats["polygons"] += 1
            elif tag == "line":
                stats["lines"] += 1
            elif tag == "g":
                stats["groups"] += 1
            elif tag in ("linearGradient", "radialGradient"):
                stats["gradients"] += 1
            elif tag == "clipPath":
                stats["clip_paths"] += 1
            elif tag in ("text", "tspan"):
                stats["text_elements"] += 1
            elif tag in ("animate", "animateTransform", "animateMotion", "set"):
                stats["has_animations"] = True
            elif tag == "title":
                stats["has_accessibility"] = True

        return stats
